CREATE TABLE IF NOT EXISTS profile(
profile_code SERIAL PRIMARY KEY NOT NULL,
wanted_job_title varchar(255) NOT NULL,
first_name varchar(255) NOT NULL,
last_name varchar(255),
email varchar(255) NOT NULL,
phone varchar(15) NOT NULL,
country varchar(255) NOT NULL,
city varchar(255) NOT NULL,
address varchar(255) NOT NULL,
postal_code int4 NOT NULL,
driving_license varchar(255),
nationality varchar,
place_of_birth varchar NOT NULL,
date_of_birth DATE NOT NULL,
photo_url varchar,
working_experiences varchar,
created_at timestamptz NULL DEFAULT CURRENT_TIMESTAMP,
updated_at timestamp NULL DEFAULT CURRENT_TIMESTAMP);