// Code generated by mockery v2.27.1. DO NOT EDIT.

package mocks

import (
	context "context"
	models "test-bpjs/v2/models"

	mock "github.com/stretchr/testify/mock"
)

// EducationRepository is an autogenerated mock type for the EducationRepository type
type EducationRepository struct {
	mock.Mock
}

// CreateEducation provides a mock function with given fields: ctx, payload
func (_m *EducationRepository) CreateEducation(ctx context.Context, payload *models.Education) (*models.EducationDTO, error) {
	ret := _m.Called(ctx, payload)

	var r0 *models.EducationDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Education) (*models.EducationDTO, error)); ok {
		return rf(ctx, payload)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.Education) *models.EducationDTO); ok {
		r0 = rf(ctx, payload)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.EducationDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.Education) error); ok {
		r1 = rf(ctx, payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteEducation provides a mock function with given fields: ctx, code, id
func (_m *EducationRepository) DeleteEducation(ctx context.Context, code int, id int) error {
	ret := _m.Called(ctx, code, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = rf(ctx, code, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetEducationByProfileCode provides a mock function with given fields: ctx, code
func (_m *EducationRepository) GetEducationByProfileCode(ctx context.Context, code int) ([]*models.EducationDTO, error) {
	ret := _m.Called(ctx, code)

	var r0 []*models.EducationDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]*models.EducationDTO, error)); ok {
		return rf(ctx, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []*models.EducationDTO); ok {
		r0 = rf(ctx, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.EducationDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewEducationRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewEducationRepository creates a new instance of EducationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewEducationRepository(t mockConstructorTestingTNewEducationRepository) *EducationRepository {
	mock := &EducationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
